name: Create GCS Bucket

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'Name of the GCS bucket to create'
        required: true
        type: string

permissions:
  contents: read
  id-token: write   # required for OIDC token exchange

jobs:
  create-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/599893116274/locations/global/workloadIdentityPools/github-pool-bucket/providers/github-provider"
          service_account: "github-actions-bucket@gcpproject-490711.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Create bucket
        run: |
          gsutil mb -p gcpproject-490711 -l us-central1 gs://${{ inputs.bucket_name }}/
